version: "3.2"
services:

  redis:
    image: "redis"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis_data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
